# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'photopizza' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for photopizza
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'SwiftyJSON'	
  pod 'DKImagePickerController'
  
  target 'photopizzaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
