# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'vuepal' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vuepal
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'SwiftyJSON'	
  pod 'DKImagePickerController', :git => 'https://github.com/Pastromhaug/DKImagePickerController.git'
  pod 'Agrume', :git => 'https://github.com/JanGorman/Agrume.git'
  
  target 'vuepalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
